# wrangler.toml
# Configuration for the Cloudflare Logging Worker.
name = "divortio-logdo"
main = "src/worker.mjs"
compatibility_date = "2025-08-21"

minify = true
workers_dev = false

[placement]
mode = "smart"

[triggers]
crons = ["0 * * * *"] # At the start of every hour

[[durable_objects.bindings]]
name = "LOG_BATCHER"
class_name = "LogBatcher"

[[d1_databases]]
binding = "LOGGING_DB"
database_name = "production-logs"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # <-- Replace with your actual D1 Database ID

# ====================================================================================
# KV Namespace Binding for State Snapshots
# ====================================================================================
[[kv_namespaces]]
binding = "LOGDO_STATE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # <-- Replace with your new KV namespace ID

# ====================================================================================
# Analytics Engine Bindings for Operational Metrics
# ====================================================================================
[[analytics_engine_datasets]]
binding = "METRICS_BATCH_WRITES"
dataset = "logdo_batch_writes"

[[analytics_engine_datasets]]
binding = "METRICS_SCHEMA_MIGRATIONS"
dataset = "logdo_schema_migrations"

[[analytics_engine_datasets]]
binding = "METRICS_DATA_PRUNING"
dataset = "logdo_data_pruning"


# ====================================================================================
# Environment Variables for Configuration
# ====================================================================================
[vars]

# --- Core Batching Configuration ---
BATCH_INTERVAL_MS = 10000
MAX_BATCH_SIZE = 200
MAX_BODY_SIZE = 10240

# --- Default Firehose Configuration ---
# These settings are used to create the mandatory firehose log route.
LOG_HOSE_TABLE = "log_firehose"
# LOG_HOSE_FILTERS =

# --- Optional Retention Policy for the Default Firehose ---
LOG_HOSE_RETENTION_DAYS = 90
LOG_HOSE_PRUNING_INTERVAL_DAYS = 1