# wrangler.toml
# Configuration for the Cloudflare Logging Worker.
name = "divortio-logdo"
main = "src/worker.mjs"
compatibility_date = "2025-08-21"

minify = true
workers_dev = false

[placement]
mode = "smart"

[[durable_objects.bindings]]
name = "LOG_BATCHER"
class_name = "LogBatcher"

[[d1_databases]]
binding = "LOGGING_DB"
database_name = "production-logs"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # <-- Replace with your actual D1 Database ID

# ====================================================================================
# Environment Variables for Configuration
# ====================================================================================
[vars]

# --- Core Batching Configuration ---
BATCH_INTERVAL_MS = 10000
MAX_BATCH_SIZE = 200
MAX_BODY_SIZE = 10240

# --- Default Firehose Configuration ---
# This is used ONLY if a `_userLogRoutes.mjs` file is NOT present at the project root.
# Defines the table name for the default, unfiltered log stream.
LOG_HOSE_TABLE = "log_firehose"

# Optional filter for the default firehose. If undefined, all requests are logged.
# Example: LOG_HOSE_FILTERS = '[{"url.pathname": {"startsWith": "/api/"}}]'
# LOG_HOSE_FILTERS =

# --- User-Defined Log Routing ---
# To enable the advanced Log Routing Pipeline, create a `_userLogRoutes.mjs` file
# in the root of your project. If that file exists and contains routes, it will
# completely override the LOG_HOSE_TABLE and LOG_HOSE_FILTERS variables.